name: Run Python Script Daily

on:
  schedule:
    - cron: '15 12 * * *'  # At 08:00 UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the runner environment
    environment: WebScrape

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROP_BOX_TOKEN }}
      run: python FuelScraper.py
