name: Retrieve secrets 
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: WebScrape

    steps:
      - name: Set up environment variable
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROP_BOX_TOKEN }}
        run: echo "DROPBOX_ACCESS_TOKEN is $DROPBOX_ACCESS_TOKEN"
