name: Retrieve secrets 
on:
  workflow_dispatch:
jobs:
  log-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo ${{ secrets.DROPBOXTOKEN }} # prints ***
