name: Retrieve secrets 
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the runner environment
    environment: WebScrape

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROP_BOX_TOKEN }}
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY}}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET}}
      run: python FuelScraper.py
