name: Retrieve secrets 
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOXTOKEN }}
    - run: echo DROPBOX_ACCESS_TOKEN
      
